### ISSUE TITLE
Declaring parameter fails unless value and descriptor are provided

### ISSUE THREAD

**Issue by kyrofa** [ros2/rclpy#369]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - From source
- Version or commit hash:
  - 0be24021af4269ce7c83fe9db550e326a8428a9b
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue
Write the following node:
```
import rclpy
from rclpy.node import Node


class MyNode(Node):
    def __init__(self):
        super().__init__("foo")

        self.declare_parameter("my_parameter")


def main(args=None):
    rclpy.init(args=args)
    node = MyNode()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()


if __name__ == "__main__":
    main()
```

#### Expected behavior
The node should be completely useless, but run. And have a parameter available.

#### Actual behavior

Traceback with "rclpy.exceptions.ParameterNotDeclaredException: ('Invalid access to undeclared parameter(s)', 'my_parameter')"

#### Additional information

The only way this works is if one supplies the _optional_ fields `value` and `descriptor` in the `declare_parameter()` function. I'd say either these need to actually be optional and work by default, or actually be required in the API.

**Comment by ivanpauno** [comment]
Adding `value` is enough for making it work (descriptor is not required).
This also looks strange to me, maybe @jubeira knows.

Note:
For making it work, I also changed:
```python3
rclpy.spin()
```
to:
```python3
rclpy.spin(node)
```

**Comment by kyrofa** [comment]
Whoops, missed that, thanks @ivanpauno. I updated the example.

**Comment by jubeira** [comment]
Hi @kyrofa, thanks for the report.

Prior to Dashing, setting a parameter with `NOT_SET` value would delete an existing parameter (i.e. parameters not set are not stored at all). Following that line, I'd say it's fine that declaring a parameter with no initial value does not actually store anything.
On the other hand, having the value as optional allows not specifying anything when a parameter override is specified in the node (or via YAML file), because the parameter will take the override as the initial value. In the code below, it shouldn't be necessary to send a value for `initial_foo`, as it will actually be set with the override:

https://github.com/ros2/rclpy/blob/597637c5cb8d1528990021fff25e32451e1587a4/rclpy/test/test_node.py#L377-L399

L378 can be replaced with a declaration without value:
```python
self.node.declare_parameter('initial_foo')
```

I'm not sure if it makes sense to declare a parameter without any initial value (no value in the method call nor a parameter override). I'm inclined to say it doesn't, and that a parameter declared with no initial value is actually an error. The exception you are getting sounds a bit misleading though; perhaps there is room for improvement on that end.
@wjwwood I'd like to hear your opinion on this; I can send a patch if required.

**Comment by wjwwood** [comment]
Calling declare with just a name and no value is fine. It just defaults to the not set value. You can do this in rclcpp already. I think the rclpy signature should be updated to allow it. In the meantime you can just explicitly pass a default initialized parameter value there, which will have the same behavior.

**Comment by wjwwood** [comment]
Also setting a value to not set still undeclared it in dashing. See: https://github.com/ros2/rclcpp/blob/0ae3da49e705eb2a019704c85fd0bb15ec4e968b/rclcpp/include/rclcpp/node.hpp#L527
