### ISSUE TITLE
Node.destroy_node() does not return bool

### ISSUE THREAD

**Issue by cyuanli** [ros2/rclpy#886]
#### Expected behavior

When calling `Ǹode.destroy_node()`, a `bool` should be returned as specified in the function declaration.

#### Actual behavior

The implementation does not return anything.

**Comment by clalancette** [comment]
It shouldn't return a bool; there is no way that it can fail.  The current implementation is correct, but the annotation is wrong.  This was fixed in Rolling as part of 48c785091d2f7b00c9737a0e65e90f6672558323 .

We can't backport that whole change (as it is much too large), but we could backport just the fix to the annotation for `destroy_node`.  @cyuanli if you'd like to open a PR to do that, it would be appreciated.

**Comment by saratrajput** [comment]
Hi @clalancette . Is this issue still open and if yes, can I work on it?

**Comment by sloretz** [comment]
@saratrajput It's still open, and yes you may work on it. It means removing the `-> bool` annotation on a PR targeting the `galactic` branch.

https://github.com/ros2/rclpy/blob/133bb0721afaf4d376cdc1066d1f6dfac6b01a73/rclpy/rclpy/node.py#L1653

**Comment by subhajit20** [comment]
@clalancette  is this issue still  open ?

**Comment by clalancette** [comment]
Nope, this was solved long ago.
